# Generated by Django 4.1.2 on 2022-10-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
